TABLE_LEAGUES, TABLE_FIXTURES, TABLE_ODDS, TABLE_RESULTS, TABLE_BETS, TABLE_USERS = 'leagues', 'fixtures', 'odds', 'results', 'bets', 'users'

SPORTS = dict()
SPORTS.update({'Soccer': 29})
SPORTS.update({'Basketball': 4})
SPORTS.update({'Tennis': 33})
SPORTS.update({'Baseball': 3})
SPORTS.update({'Football': 15})
SPORTS.update({'Hockey': 19})
SPORTS.update({'Rugby League': 26})
SPORTS.update({'Rugby Union': 27})
SPORTS.update({'Darts': 10})
SPORTS.update({'Cricket': 8})
SPORTS.update({'Golf': 17})
SPORTS.update({'Handball': 18})
SPORTS.update({'Snooker': 28})
SPORTS.update({'Volleyball': 34})
SPORTS.update({'Aussie Rules': 39})
SPORTS.update({'Alpine Skiing': 40})
SPORTS.update({'Athletics': 56})
SPORTS.update({'Badminton': 1})
SPORTS.update({'Bandy': 2})
SPORTS.update({'Beach Volleyball': 5})
SPORTS.update({'Biathlon': 41})
SPORTS.update({'Boxing': 6})
SPORTS.update({'Chess': 7})
SPORTS.update({'Cross Country': 43})
SPORTS.update({'Crossfit': 57})
SPORTS.update({'Curling': 9})
SPORTS.update({'Cycling': 45})
SPORTS.update({'Entertainment': 58})
SPORTS.update({'Field Hockey': 13})
SPORTS.update({'Formula 1': 44})
SPORTS.update({'Futsal': 16})
SPORTS.update({'Mixed Martial Arts': 22})
SPORTS.update({'Motorsport': 63})
SPORTS.update({'Olympics': 55})
SPORTS.update({'Padel Tennis': 37})
SPORTS.update({'Ski Jumping': 42})
SPORTS.update({'Softball': 30})
SPORTS.update({'Squash': 31})
SPORTS.update({'Sumo': 65})
SPORTS.update({'Table Tennis': 32})
SPORTS.update({'Water Polo': 36})
